import type { LucideIcon } from 'lucide-react'
import {
  Baby,
  Banknote,
  Bike,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Cake,
  Camera,
  Car,
  Cat,
  CircleDollarSign,
  CircleEllipsis,
  CirclePlus,
  Clapperboard,
  Coffee,
  CreditCard,
  Dog,
  Dumbbell,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Hammer,
  Headphones,
  Heart,
  HeartPulse,
  House,
  Laptop,
  Lightbulb,
  Music,
  PawPrint,
  Phone,
  PiggyBank,
  Pill,
  Plane,
  Plug,
  Receipt,
  Repeat,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  TrainFront,
  TreePalm,
  Tv,
  Umbrella,
  User,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wrench,
} from 'lucide-react'
import { cn } from '@/lib/utils'

export const EMOJI_PREFIX = 'emoji:'

export const CATEGORY_ICON_NAMES = [
  'Wallet',
  'CircleDollarSign',
  'Banknote',
  'CreditCard',
  'PiggyBank',
  'Receipt',
  'UtensilsCrossed',
  'Coffee',
  'ShoppingBag',
  'ShoppingCart',
  'Car',
  'Bus',
  'TrainFront',
  'Bike',
  'Fuel',
  'Plane',
  'House',
  'Building2',
  'Plug',
  'Wifi',
  'Lightbulb',
  'HeartPulse',
  'Stethoscope',
  'Pill',
  'Dumbbell',
  'Clapperboard',
  'Tv',
  'Music',
  'Headphones',
  'Gamepad2',
  'Camera',
  'BookOpen',
  'GraduationCap',
  'Laptop',
  'Smartphone',
  'Phone',
  'Briefcase',
  'Hammer',
  'Wrench',
  'Shirt',
  'Sparkles',
  'Gift',
  'Cake',
  'Baby',
  'User',
  'Heart',
  'PawPrint',
  'Dog',
  'Cat',
  'TreePalm',
  'Umbrella',
  'Repeat',
  'CircleEllipsis',
  'CirclePlus',
] as const

export type CategoryIconName = (typeof CATEGORY_ICON_NAMES)[number]

const ICONS: Record<string, LucideIcon> = {
  Baby,
  Banknote,
  Bike,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Cake,
  Camera,
  Car,
  Cat,
  CircleDollarSign,
  CircleEllipsis,
  CirclePlus,
  Clapperboard,
  Coffee,
  CreditCard,
  Dog,
  Dumbbell,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Hammer,
  Headphones,
  Heart,
  HeartPulse,
  House,
  Laptop,
  Lightbulb,
  Music,
  PawPrint,
  Phone,
  PiggyBank,
  Pill,
  Plane,
  Plug,
  Receipt,
  Repeat,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  TrainFront,
  TreePalm,
  Palmtree: TreePalm,
  Tv,
  Umbrella,
  User,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wrench,
}

export const CATEGORY_EMOJIS = [
  { emoji: '💰', label: 'money' },
  { emoji: '💵', label: 'cash' },
  { emoji: '💳', label: 'card' },
  { emoji: '🏦', label: 'bank' },
  { emoji: '📈', label: 'chart' },
  { emoji: '🪙', label: 'coin' },
  { emoji: '🤑', label: 'rich' },
  { emoji: '💸', label: 'spend' },
  { emoji: '🧾', label: 'receipt bill' },
  { emoji: '🏠', label: 'home house' },
  { emoji: '🏢', label: 'office' },
  { emoji: '🔑', label: 'rent key' },
  { emoji: '🛋️', label: 'furniture' },
  { emoji: '💡', label: 'utilities' },
  { emoji: '🔌', label: 'electric' },
  { emoji: '💧', label: 'water' },
  { emoji: '🍔', label: 'food burger' },
  { emoji: '🍕', label: 'pizza' },
  { emoji: '🍜', label: 'noodles' },
  { emoji: '🍱', label: 'lunch' },
  { emoji: '🥗', label: 'salad' },
  { emoji: '☕', label: 'coffee' },
  { emoji: '🍺', label: 'drinks' },
  { emoji: '🍷', label: 'wine' },
  { emoji: '🛒', label: 'groceries' },
  { emoji: '🛍️', label: 'shopping' },
  { emoji: '👗', label: 'clothes' },
  { emoji: '👟', label: 'shoes' },
  { emoji: '💄', label: 'beauty' },
  { emoji: '🚗', label: 'car' },
  { emoji: '🚕', label: 'taxi' },
  { emoji: '🚌', label: 'bus' },
  { emoji: '🚇', label: 'metro' },
  { emoji: '⛽', label: 'fuel' },
  { emoji: '✈️', label: 'flight' },
  { emoji: '🏨', label: 'hotel' },
  { emoji: '🧳', label: 'travel' },
  { emoji: '🏥', label: 'hospital' },
  { emoji: '💊', label: 'medicine' },
  { emoji: '🩺', label: 'health' },
  { emoji: '🏋️', label: 'gym' },
  { emoji: '🎬', label: 'movies' },
  { emoji: '🎮', label: 'games' },
  { emoji: '🎵', label: 'music' },
  { emoji: '📺', label: 'tv' },
  { emoji: '📱', label: 'phone' },
  { emoji: '💻', label: 'laptop' },
  { emoji: '📚', label: 'education' },
  { emoji: '🎓', label: 'school' },
  { emoji: '👶', label: 'kids' },
  { emoji: '🎁', label: 'gift' },
  { emoji: '🎉', label: 'party' },
  { emoji: '🐶', label: 'pet' },
  { emoji: '⚽', label: 'sports' },
  { emoji: '💇', label: 'salon' },
  { emoji: '🛠️', label: 'repair' },
  { emoji: '📦', label: 'delivery' },
  { emoji: '📮', label: 'post' },
  { emoji: '💼', label: 'work' },
  { emoji: '🧑‍💻', label: 'freelance' },
  { emoji: '💎', label: 'luxury' },
  { emoji: '🪴', label: 'plants' },
  { emoji: '🧼', label: 'household' },
  { emoji: '🧸', label: 'toys' },
  { emoji: '❤️', label: 'personal' },
  { emoji: '⭐', label: 'star' },
  { emoji: '🔥', label: 'hot' },
  { emoji: '🌈', label: 'other' },
] as const

export function toEmojiIcon(emoji: string) {
  return `${EMOJI_PREFIX}${emoji}`
}

export function readEmoji(name: string) {
  if (name.startsWith(EMOJI_PREFIX)) return name.slice(EMOJI_PREFIX.length)
  return null
}

export function CategoryIcon({
  name,
  className,
}: {
  name: string
  className?: string
}) {
  const emoji = readEmoji(name)
  if (emoji) {
    return (
      <span className={cn('inline-flex items-center justify-center leading-none', className)} aria-hidden>
        <span className="text-[1.05em]">{emoji}</span>
      </span>
    )
  }
  const Icon = ICONS[name] ?? CircleEllipsis
  return <Icon className={className} strokeWidth={1.75} aria-hidden />
}
